In [1]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.7.0


In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [3]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [4]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.07923931,  0.00330023,  0.1328589 , -0.42604318, -0.925887  ,
        -0.24694741,  0.09997603,  0.8612975 ,  0.4882567 ,  0.0904607 ]],
      dtype=float32)

In [5]:
tf.nn.softmax(predictions).numpy()

array([[0.08326302, 0.09042709, 0.10293551, 0.05886229, 0.03570735,
        0.07040726, 0.09960574, 0.21326621, 0.14686303, 0.09866245]],
      dtype=float32)

In [6]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [7]:
loss_fn(y_train[:1], predictions).numpy()

2.653459

In [8]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [9]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2991 - accuracy: 0.9131
Epoch 2/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1440 - accuracy: 0.9567
Epoch 3/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1098 - accuracy: 0.9671
Epoch 4/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0874 - accuracy: 0.9735
Epoch 5/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0759 - accuracy: 0.9756


In [10]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0746 - accuracy: 0.9767 - 475ms/epoch - 2ms/step


[0.0745982974767685, 0.9767000079154968]

In [11]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [12]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[8.3953843e-08, 2.4437835e-08, 6.1024516e-06, 2.2651862e-04,
        3.1086259e-11, 2.4641533e-08, 2.3010028e-13, 9.9976605e-01,
        1.7771387e-07, 1.0357701e-06],
       [6.4735856e-10, 9.9834642e-06, 9.9998891e-01, 4.3182129e-07,
        1.1031978e-16, 1.2469398e-07, 4.5744497e-09, 3.7590767e-15,
        4.3619622e-07, 4.1223039e-16],
       [3.5232637e-09, 9.9979073e-01, 2.0724530e-05, 4.4958449e-07,
        8.5618958e-05, 4.1362324e-07, 4.4697282e-07, 7.8305500e-05,
        2.3210705e-05, 2.2049671e-08],
       [9.9993050e-01, 1.4058248e-09, 3.8305392e-05, 1.6423013e-06,
        5.6337853e-08, 2.1124451e-05, 5.7117909e-06, 1.3134952e-06,
        2.0489402e-07, 1.1477089e-06],
       [9.6942331e-06, 6.2423333e-10, 1.1160930e-05, 7.9009396e-07,
        9.9155879e-01, 8.1338703e-06, 7.9815038e-07, 7.4078846e-05,
        5.4089605e-06, 8.3312523e-03]], dtype=float32)>

In [15]:

sys_details = tf.sysconfig.get_build_info()
cuda_version = sys_details["cuda_version"]
print(cuda_version)

64_112


In [16]:
  
cudnn_version = sys_details["cudnn_version"]  
print(cudnn_version)

64_8


In [18]:
cpu_compiler = sys_details["cpu_compiler"]  
print(cpu_compiler)

C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.27.29110/bin/HostX64/x64/cl.exe


In [19]:
cuda_compute_capabilities = sys_details["cuda_compute_capabilities"]  
print(cuda_compute_capabilities)

['sm_35', 'sm_50', 'sm_60', 'sm_70', 'sm_75', 'compute_80']


In [20]:
tf.Session()

AttributeError: module 'tensorflow' has no attribute 'Session'

In [22]:
import tensorflow as tf 

if tf.test.gpu_device_name(): 

    print('Default GPU Device:{}'.format(tf.test.gpu_device_name()))

else:

   print("Please install GPU version of TF")

Default GPU Device:/device:GPU:0
